#include "AmpPreamp.h"

AmpPreamp::AmpPreamp()
    : oversampler(2, 2, juce::dsp::Oversampling<float>::filterHalfBandPolyphaseIIR)
{
}

void AmpPreamp::prepare(double sampleRate, int samplesPerBlock, int numChannels)
{
    currentSampleRate = sampleRate;

    oversampler.initProcessing(static_cast<juce::uint32>(samplesPerBlock));
    oversampler.reset();

    juce::dsp::ProcessSpec spec;
    spec.sampleRate = sampleRate;
    spec.maximumBlockSize = static_cast<juce::uint32>(samplesPerBlock);
    spec.numChannels = static_cast<juce::uint32>(numChannels);

    inputHighPass.prepare(spec);
    interstageHighPass.prepare(spec);
    interstageLowPass.prepare(spec);
    interstageHighPass2.prepare(spec);
    interstageLowPass2.prepare(spec);
    fizzLowPass.prepare(spec);

    gainStage1.prepare(sampleRate);
    gainStage2.prepare(sampleRate);
    gainStage3.prepare(sampleRate);
    toneStack.prepare(sampleRate, samplesPerBlock, numChannels);
}

void AmpPreamp::processBlock(
    juce::AudioBuffer<float> &buffer,
    float inputHighPassHz,
    bool dirty,
    float gain1,
    float bias1,
    float interstageHighPassHz,
    float gain2,
    float interstageHighPassHz2,
    float gain3,
    float bassDb,
    float lowerMidDb,
    float upperMidDb,
    float trebleDb,
    float fizzLowPassHz,
    float masterLevel)
{
    *inputHighPass.state =
        *juce::dsp::IIR::Coefficients<float>::makeHighPass(currentSampleRate, inputHighPassHz);

    *interstageHighPass.state =
        *juce::dsp::IIR::Coefficients<float>::makeHighPass(currentSampleRate, interstageHighPassHz);

    *interstageHighPass2.state = *juce::dsp::IIR::Coefficients<float>::makeHighPass(
        currentSampleRate, interstageHighPassHz2);

    *fizzLowPass.state =
        *juce::dsp::IIR::Coefficients<float>::makeLowPass(currentSampleRate, fizzLowPassHz);

    *interstageLowPass.state =
        *juce::dsp::IIR::Coefficients<float>::makeLowPass(currentSampleRate, 7000.0f);

    *interstageLowPass2.state =
        *juce::dsp::IIR::Coefficients<float>::makeLowPass(currentSampleRate, 6500.0f);

    juce::dsp::AudioBlock<float> block(buffer);
    juce::dsp::ProcessContextReplacing<float> context(block);

    // Input high-pass: tightens low end before distortion.
    inputHighPass.process(context);

    auto oversampledBlock = oversampler.processSamplesUp(block);
    juce::dsp::ProcessContextReplacing<float> oversampledContext(oversampledBlock);

    if (dirty) {
        // Gain stage 1
        for (size_t channel = 0; channel < oversampledBlock.getNumChannels(); ++channel) {
            auto *data = oversampledBlock.getChannelPointer(channel);

            for (size_t i = 0; i < oversampledBlock.getNumSamples(); ++i)
                data[i] = gainStage1.processSample(data[i], gain1, bias1);
        }

        // Interstage high-pass 1
        interstageHighPass.process(oversampledContext);
        interstageLowPass.process(oversampledContext);

        // Gain stage 2
        for (size_t channel = 0; channel < oversampledBlock.getNumChannels(); ++channel) {
            auto *data = oversampledBlock.getChannelPointer(channel);

            for (size_t i = 0; i < oversampledBlock.getNumSamples(); ++i)
                data[i] = gainStage2.processSample(data[i], gain2);
        }

        // Interstage high-pass 2
        interstageHighPass2.process(oversampledContext);
        interstageLowPass2.process(oversampledContext);

        // Gain stage 3
        for (size_t channel = 0; channel < oversampledBlock.getNumChannels(); ++channel) {
            auto *data = oversampledBlock.getChannelPointer(channel);

            for (size_t i = 0; i < oversampledBlock.getNumSamples(); ++i)
                data[i] = gainStage3.processSample(data[i], gain3);
        }
    }

    oversampler.processSamplesDown(block);

    // Tone stack
    toneStack.processBlock(buffer, bassDb, lowerMidDb, upperMidDb, trebleDb);

    // Post-distortion low-pass: removes fizz generated by clipping.
    fizzLowPass.process(context);

    // Master level: how hard to hit the power amp.
    buffer.applyGain(masterLevel);
}
